config/routes.rb
Rails.application.routes.draw do


  resources :books do
    resources :comments
    member do
      put "like", to: "books#liked"
      put "dislike", to: "books#disliked"
    end
  end


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :profiles, only: [:index, :show]
  
  root "books#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments

  acts_as_votable

  mount_uploader :image, ImageUploader

	
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @sidebar = true
    @categories = Category.all

    if params[:category] 
    @books = Book.where(category_id: params[:category])
      if @books.size.zero? 
        @books = Book.all
      end 
    else 
      @books = Book.all
    end
    
    

  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  def liked 
    @book = Book.find(params[:id])
    @book.liked_by current_user
    redirect_to books_path
  end  

  def unliked
    @book = Book.find(params[:id])
    @book.unliked_by current_user
    redirect_to books_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :pages, :image, :abstract, :user_id, :category_id)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, t('Título') %>
    <%= form.text_field :title, id: :book_title %>
  </div>

  <div class="field">
    <%= form.label :author, t('Autor') %>
    <%= form.text_field :author, id: :book_author %>
  </div>

  <div class="field">
    <%= form.label :pages, t('Número de páginas') %>
    <%= form.number_field :pages, id: :book_pages %>
  </div>

  <div class="field">
    <%= form.label :image, t('Portada') %>
    <%= form.file_field :image, id: :book_image %>
  </div>

  <div class="field">
    <%= form.label :abstract, t('Resumen') %>
    <%= form.text_area :abstract, id: :book_abstract %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, id: :book_user_id, value: current_user.id %>
  </div>

  <div class="field">
    <%= form.label :category_id, t('Categoría') %>
    <%= form.collection_select :category_id, Category.all, :id, :name, include_blank: true %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <% @books.each_slice(3) do |group| %>
  <div class="row">
    <% group.collect do |book| %>
    <div class="col-sm-3 col-lg-3 col-md-3">
      <%= link_to "#{book.user.first_name}", profile_path(book.user) %> is the owner of this book
      <div class="thumbnail">
        <%= image_tag("#{book.image_url}" , height: '80', width: '60')  %>
       <div class="caption">
        <h4>  <%= link_to "#{book.title}", book_path(book)%></h4>
        <h5>(<%= book.pages %> pag.) <%= book.author %></h5>
        <h5><i><%= book.category.name %></i> </h5>
        <p><%= book.abstract %></p>
        <div class="vote_button">
          <div class="row">
            <div class="col-sm-6">
              <%= link_to "Like", like_book_path(book), method: :put, class: "btn btn-success " %>
            </div>
            <div class="col-sm-6">
              <%= link_to "Dislike", dislike_book_path(book), method: :put, class: "btn btn-warning" %>
            </div>
          </div> 
        </div>
       </div>
      </div>
   </div>
    <% end %>
  </div>
  <% end %>
  <br>
</div>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<div class="well">
  <p>
    <strong>Title:</strong>
    <%= @book.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= @book.author %>
  </p>

  <p>
    <strong>Pages:</strong>
    <%= @book.pages %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= image_tag(@book.image_url, :width => 600, :height => 600) if @book.image.present? %>
  </p>

  <p>
    <strong>Abstract:</strong>
    <%= @book.abstract %>
  </p>

  <p>
    <strong>User:</strong>
    <%= @book.user.first_name %> <%= @book.user.last_name %>
  </p>

  <hr>

  
</div>

<% @book.comments.each do |comment| %>
  <div class="container">
    <div class="well">
      <p><%= comment.user.first_name %> say:</p>
      <p><%= comment.comment %></p> 
    </div>
  </div>
<%end %>


  <% if signed_in? %>
    <%= form_for([@book, @book.comments.build]) do |f| %>
      <%= f.label :coment, class: 'control-label'  %>
      <%= f.text_area :comment, class: 'form-control' %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :book_id, value: @book.id %>
      <br>
      <%= f.submit %>
    <%end %> 
  <%end %>
  <br>
  
  

  <%= link_to 'Back', books_path %>